version: '3.8'
services:
  mariadb:
    build: ./requirements/mariadb 
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/lib/mysql
    networks:
      - oupi

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress 
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_database:/var/www/html
    networks:
      - goupi
      - oupi
  
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_database:/var/www/html
    networks:
      - goupi
  
volumes:
  wordpress_database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/habouda42/data/wordpress
    
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/habouda42/data/mariadb

networks:
  oupi:
    driver: bridge
  goupi:
    driver: bridge