version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb 
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql  # Fixed: MariaDB should use mariadb_data
    networks:
      - oupi

  wordpress:
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress 
    container_name: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html  # Fixed: WordPress should use wordpress_data
    networks:
      - goupi
      - oupi
  
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html  # Fixed: Nginx needs WordPress files, not MariaDB
    networks:
      - goupi

  redis:
    build: ./bonus/redis
    container_name: redis
    restart: always
    networks:
      - oupi

volumes:
  mariadb_data:  # Renamed for clarity
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/habouda42/data/mariadb  # MariaDB data goes here
    
  wordpress_data:  # Renamed for clarity
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/habouda42/data/wordpress  # WordPress files go here

networks:
  oupi:
    driver: bridge
  goupi:
    driver: bridge